version: '3.7'
services:
    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        restart: always
        volumes:
            - /app/node_modules
            - ./frontend:/app
        container_name: tave_frontend
        stdin_open: true

    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        container_name: tave_nginx
        ports:
            - '3000:80'

    backend:
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        container_name: tave_backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: tave123
            MYSQL_DATABASE: tave
            MYSQL_PORT: 3306

            S3_KEYID: ${S3_KEYID}
            S3_PRIVATE_KEY: ${S3_PRIVATE_KEY}
            REGION: ${REGION}
            BUCKET_NAME: ${BUCKET_NAME}

            NODE_ENV: development

    mysql:
        build: ./mysql
        restart: unless-stopped
        container_name: tave_mysql
        ports:
            - '3307:3306'
        volumes:
            - ./mysql/mysql_data:/var/lib/mysql
            - ./mysql/sqls/:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: tave123
            MYSQL_DATABASE: tave
        cap_add:
            - SYS_NICE
